In [1]:
import numpy as np

In [4]:
"""
Computing reciprocalls in loops
"""
#function for computing reciprocals using looping

def compute_reciprocals(values):
    output = np. empty(len(values))
    for i in range(len(values)):
        output[i] =1.0/values[i]
    return output

np.random.seed(0)
values = np.random.randint(1,10,size=5)
print(values)

output = compute_reciprocals(values)
print(output)

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [12]:
"""
Comparuison : Loop vs ufuncs(vectorized)
"""
big_array = np.random.randint(1, 100, size = 1000000)
print(big_array)

#looping on a big array

#magic function 
%timeit compute_reciprocals(big_array) 

[84 21 18 ... 51 17 60]
3.58 s ± 268 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
# vectorized operations

%timeit 1/ big_array

3.43 ms ± 373 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)
print(arr1, arr2)

arr1 =arr1 -2 
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10,size = (3,5))
print(arr4)

print(arr4**2)



[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [15]:
"""
Ufuncs: absolute value
"""

x= np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [16]:
"""
UFuncs: Trigonometric Functions
"""

theta = np.linspace(0,np.pi,3)
print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [17]:
"""
UFuncs : aggregation
"""

x = np.arange(1,5)
print(x)
aggr = np.add.reduce(x)
print(aggr)

aggr= np.multiply.reduce(x)
print(aggr)

accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
10
24
[ 1  3  6 10]
[ 1  2  6 24]


In [18]:
np.random.seed(3)

arr = np.random.rand(1000000)
print(arr)

print("sum = ", np.sum(arr))


[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum =  500422.19897015305


In [19]:
%timeit sum(arr)

109 ms ± 2.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
%timeit np.sum(arr)

1.22 ms ± 17.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
#other aggr.functions

print(arr)
print('max = ', np.max(arr))
print('min = ', np.min(arr))
print('mean = ', np.mean(arr))
print('median =', np.median(arr))
print('percentile = ' ,np.percentile(arr,90))

print(np.any(arr>1))
print(np.all(arr>0))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
max =  0.9999996367889004
min =  1.5496004267534502e-06
mean =  0.500422198970153
median = 0.5005659265960778
percentile =  0.9001765340710965
False
True


In [22]:
#multi dimensional aggregates

np.random.seed(5)
arr= np.random.randint(10, size=(3,4))
print(arr)

print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
