In [2]:
import numpy as np

In [20]:
#Creatin a Numpy Araay
my_list = [1,2,3,4,5]

my_array = np.array(my_list)
print(my_array)

arr =np.array([1,2])
print(arr)

[1 2 3 4 5]
[1 2]


In [21]:
# dtype attribute

a = np.array([1,"a",True])
print(a.dtype)

b = np.array([1,2,3])
print(b.dtype)

c = np.array([1.1,2,3])
print(c.dtype) 

<U11
int32
float64


In [23]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(getsizeof(lst))

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(getsizeof(arr))

136
144


In [26]:
prices=[30, 25, 40, 20, 20, 35, 50, 35]
price_arr = np.array(prices)
price_arr -= 5
print(price_arr)

[25 20 35 15 15 30 45 30]


In [29]:
# opereation an np.sqrt

lst = [1,2,3]
arr = np.array(lst)
arr = np.sqrt(arr)
print(arr)

[1.         1.41421356 1.73205081]


In [39]:
"""
Exercise
"""
test_1 = np.array ([92, 94, 88, 91, 87])
test_2 = np.array ([79, 100, 86, 93, 91])
test_3 = np.array ([87, 85, 72, 90, 92])
test_3_fixed = test_3 + 2
print(test_3_fixed)
total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)
final_grade = total_grade/3
print(final_grade)

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [47]:
jeremy_test_2 = test_2[3]
manual_adwoa_test_1 = [test_1 [1],test_1[2]]
print(manual_adwoa_test_1)

[94, 88]


In [64]:
student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]


In [65]:
print(student_scores[2][0])

87


In [68]:
print(student_scores[:, 3])

[91 93 90]


In [73]:
"""
Logical Operation with Arrays
"""

#masking
arr = np.array([1,2,3,4,5,6,7,8,9])
mask = arr > 5
print(mask)

[False False False False False  True  True  True  True]


In [80]:
#select using logical operation '&','/'
selected = arr[(arr>5) | (arr<3)]
print(selected)

[1 2 6 7 8 9]
