In [1]:
import numpy as np

In [5]:
"""
Numpy Array Attributes
"""

print(np.arange(3)) # stop
print(np.arange(2,5)) # start, stop
print(np.arange(1,9,2)) # start, stop, step

[0 1 2]
[2 3 4]
[1 3 5 7]


In [11]:
# random number generator
arr1 = np.random.randint(10, size=(5)) #0~9
print(arr1)

arr2 = np.random.randint(100,size = (3, 5))
print(arr2)

arr3 = np.random.randint(100, size = (3, 5, 2))
print(arr3)

[3 4 3 8 9]
[[61 13 14 73  3]
 [69 82 97 96 70]
 [83 33  4 76 99]]
[[[77 46]
  [99 23]
  [31 14]
  [92 48]
  [77 46]]

 [[45 29]
  [23  3]
  [80  3]
  [13 66]
  [37 55]]

 [[88 15]
  [93 87]
  [73 61]
  [33 97]
  [ 4 70]]]


In [27]:
# Attibutes

print("arr1,ndim=" , arr1.ndim)
print("arr2,shape" , arr2.shape)
print("arr2,size" , arr2.size)
print("arr2,dtype=" , arr2.dtype)
print("arr2,itemsize=" , arr2.itemsize)

arr4 = np.array([1.5, 2.3, 3.4])
print("arr4,itemsize=" , arr4.itemsize)

print("arr2.nbytes = " , arr2.nbytes)

arr1,ndim= 1
arr2,shape (3, 5)
arr2,size 15
arr2,dtype= int32
arr2,itemsize= 4
arr4,itemsize= 8
arr2.nbytes =  60


In [41]:
"""
Subarrays as no-copy views
"""
np.random.seed(1)
arr = np.random.randint(10, size = (3,4))
print(arr,'\n')

arr_sub = arr[:2,:2]
print(arr_sub, '\n')

arr_sub[0,0] = -1
print(arr_sub,'\n')
print(arr)


[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[-1  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [46]:
# copy
np.random.seed(1)
arr = np.random.randint(10, size = (3,4))
print(arr)

arr_sub = arr[:2,:2].copy()
print(arr_sub, '\n')
arr_sub[0,0] = -1 
print(arr_sub, '\n')

print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]


In [47]:
"""
Reshapeing of Arrays
"""
arr= np.arange(1,10)
print(arr)

grid = arr.reshape(3,3)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
#np.newaxis

arr= np.array([1,2,3])
print(arr)
print("arr.ndim = ",arr.ndim)
print("arr.shape = ", arr.shape)

arr_new = arr[:, np.newaxis]
print(arr_new)
print("arr_new.ndim = ",arr_new.ndim)
print("arr_new.shape = ", arr_new.shape)


[1 2 3]
arr.ndim =  1
arr.shape =  (3,)
[[1]
 [2]
 [3]]
arr_new.ndim =  2
arr_new.shape =  (3, 1)


In [66]:
"""
Array Concatention
"""

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([7,8,9])

arr_total = np.concatenate([arr_1,arr_2,arr_3])
print(arr_total)

arr_total = np.vstack([arr_1,arr_2,arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
"""
ARray splitting
"""
arr = [1,2,3,99,99,3,2,1]
print(arr)


arr_1,arr_2 = np.split(arr,[4])
print(arr_1,arr_2)

[1, 2, 3, 99, 99, 3, 2, 1]
[ 1  2  3 99] [99  3  2  1]
