In [38]:
import pandas as pd

In [39]:
pd.__version__

'1.3.3'

In [40]:
ser = pd.Series([0.25,0.5,0.75,1.0]) #constructor method : "객체를 생성하는 매서드" 때문에 앞에 대문자
print(ser)
print(ser.shape)

print(ser.values)
print(ser.index)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
(4,)
[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


In [41]:
ser = pd.Series([0.25,0.5,0.75,1.0], index = ['a','b','c','d'])
print(ser)

print(ser['b'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5


In [42]:
dict = {'a': 1, 2: 'two', 'third': True} #dict{key1: value1 ...}
print(dict)
print(dict['third'])

{'a': 1, 2: 'two', 'third': True}
True


In [60]:
population_dict = {'California': 38332521,
'Texas': 26448193,
"New York": 19651127,
'Florida': 19552860,
'Illinois': 12882135}

print(population_dict)

population = pd.Series(population_dict)
print(population)

{'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [61]:
area_dict = {'California': 423967,'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


In [62]:
df = pd.DataFrame({'population':population, 'area':area})
print(df)

print(df.index)
print(df.columns)

df['area']

import numpy as np

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object')


In [63]:
arr = np.random.rand(3,2)
print(arr,'\n')

dff = pd.DataFrame(arr,columns = ['foo','bar'],index = ['2021-10-13','2021-10-14','2021-10-15'])
print(dff)

[[0.60859915 0.09748787]
 [0.2275443  0.35200848]
 [0.70270145 0.77973479]] 

                 foo       bar
2021-10-13  0.608599  0.097488
2021-10-14  0.227544  0.352008
2021-10-15  0.702701  0.779735


In [68]:
print(df)

df['density'] = df['population']/ df['area']
print(df)

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763
            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763


In [69]:
print(df.loc['New York'])

population    1.965113e+07
area          1.412970e+05
density       1.390767e+02
Name: New York, dtype: float64


In [73]:
print(df.values,'\n')
print(df.T, '\n')

print(df.iloc[:3,:2],'\n')

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]] 

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01   

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297 

